### ISSUE TITLE
Environment variable(s) for Steward config

### ISSUE THREAD

**Issue by cbrit** [PeggyJV/steward#111]
Rather than requiring users to pass their config toml as an argument to every single steward command, it would be good for there to be a STEWARD_CONFIG_PATH environment variable that is checked on startup and used if present. This also prevents the strange behavior of using unexpected default config values when you forget to use the `-c` parameter, such as when creating a key and it appearing in /tmp/keystore by mistake.

Not sure if [Abscissa](https://github.com/iqlusioninc/abscissa) actually supports this currently, it may require a PR there.

**Comment by hannydevelop** [comment]
I think I've seen something like this in clap, not very sure. If clap has it, Abscissa definitely will. So, I'm picking this up since I have the better experience here.
