### ISSUE TITLE
How do we manage cellar_id

### ISSUE THREAD

**Issue by hannydevelop** [PeggyJV/steward#34]
Does `cellar_id` come from existing config? or need to introduce something new here?

Here's the link to where it's needed:

https://github.com/PeggyJV/cellar_rebalancer_rs/blob/7f8f36f91423d3912c0ca7830622614c126502da/src/collector/poller.rs#L179

**Comment by hannydevelop** [comment]
@zmanian

**Comment by zmanian** [comment]
Cellar_id needs to be a pair of two strings at very least, address and chain_id

**Comment by zmanian** [comment]
so for the Ethereum based cellars it would be "contract_address, ethereum". We can require that all cellar ids be on Ethereum right now and have more sophisticated routing later.

**Comment by cbrit** [comment]
Data Science and I have been operating under the assumption that it would be something like `ethereum:0x00000000000000000000000000000000` until we got a more concrete specification.
