### ISSUE TITLE
CLI acceptance tests

### ISSUE THREAD

**Issue by EricBolten** [PeggyJV/steward#77]
Acceptance tests

- [ ] Keys command
confirm that command runs successfully, make sure mnemonic is 24 words.

**Comment by hannydevelop** [comment]
Following the acceptance tests in [Zebra](https://github.com/ZcashFoundation/zebra/blob/afb8b3d4775d89b3f9223447341bf6ce152f5c3a/zebra-test/src/command.rs), I'm writing an acceptance test for all commands in the cellar rebalancer.

**Comment by hannydevelop** [comment]
- [X] Keys command
   - [X]
