### ISSUE TITLE
Incomplete CLI command cleanup

### ISSUE THREAD

**Issue by EricBolten** [PeggyJV/steward#89]
There are a variety of CLI commands that are either incomplete or half-implemented. The most expedient thing to do for now would be to simply delete them. We can always implement further commands at a later date, and having half-finished code is cumbersome and confusing.

**Comment by hannydevelop** [comment]
1. The query command is incomplete. However, the pool pair section is functional so I'll leave that out.
2. The send command in tx/cosmos is incomplete. The same applies to the tx/eth command.
3. While the transfer command is complete, I doubt if it's useful so I'll wait for @EricBolten response.

- [x] Query command
- [x] Send command
- [ ] Transfer command

**Comment by hannydevelop** [comment]
Hello @EricBolten waiting for your input on the transfer command
